apiVersion: v1
kind: Config
clusters:
- name: "swe"
  cluster:
    server: "https://44.217.168.250/k8s/clusters/c-m-f6h57g4v"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      GN4TWpZeApPREl3TmpBZUZ3MHlOREEwTURneU16RTJORFphRncwek5EQTBNRFl5TXpFMk5EWmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE56RXlOakU0TWpBMk1Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRUhRa2EyMVhveUdMTgowZm0xVGZRL2w1KzBvK0JlMkMvTEZSMHA4Y\
      UhhUGFMNk55YkZyZW1PeXZKSHNvVDVoWUtJMVphSElTbGlocm9YCkV5S1FiTkdpMXFOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGS\
      09hL3JZK0Jrc2JZc1piZ3JpMFQ0a0gveUU3TUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFDRwp5W\
      VFadHVMRHUySzAweERjUEhBSzRWZGFmeDVSdzY0VEhvaDZuOURtbXdJZ2Y0VTRNbUFnbnJ6QXNjd\
      E10RXhSCjhsYjREKzQrZ3E2TU1ueFJTeHIySkwwPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "swe"
  user:
    token: "kubeconfig-user-mh9wpls2f4:rqwqxqm9mbjl5hkwqr9mslcjhbfg9h2krls9l29xlrdt7275n49fxb"


contexts:
- name: "swe"
  context:
    user: "swe"
    cluster: "swe"

current-context: "swe"

